export const ROUTES = {
  home: "/",
  search: "/search",
  login: "/login",
  signup: "/signup",
  transactions: {
    root: "/transactions",
    analytics: "/transactions/analytics",
  },
  settlements: {
    root: "/settlements",
  },
  disputes: {
    root: "/disputes",
  },
  refunds: {
    root: "/refunds",
    analytics: "/refunds/analytics",
  },
  reports: {
    root: "/reports",
  },
  products: {
    root: "/products",
    onlinePayments: "/products/online-payments",
    onlinePaymentsPayoutSetup: "/products/online-payments/payout-setup",
    inStorePayments: "/products/in-store-payments",
    inStoreQrSticker: "/products/in-store-payments/upi-qr-sticker",
    otherProducts: "/products/other-products",
    thirdPartyOffers: "/products/third-party-offers",
    offerEngineComingSoon: "/products/offer-engine-coming-soon",
    growthxComingSoon: "/products/growthx-coming-soon",
    giftCardsComingSoon: "/products/gift-cards-coming-soon",
    fintechApisComingSoon: "/products/fintech-apis-coming-soon",
  },
  onlinePayments: {
    root: "/online-payments",
    transactions: "/online-payments/transactions",
    settlements: "/online-payments/settlements",
    disputes: "/online-payments/disputes",
    refunds: "/online-payments/refunds",
    reports: "/online-payments/reports",
    configuration: "/online-payments/configuration",
  },
  offlinePayments: {
    root: "/offline-payments",
    transactions: "/offline-payments/transactions",
    settlements: "/offline-payments/settlements",
    disputes: "/offline-payments/disputes",
    refunds: "/offline-payments/refunds",
    reports: "/offline-payments/reports",
    manageDevices: "/offline-payments/manage-devices",
    orderDevices: "/offline-payments/order-devices",
    manageStores: "/offline-payments/manage-stores",
  },
  paymentLinks: {
    root: "/payment-links",
    all: "/payment-links/all",
    transactions: "/payment-links/transactions",
    settlements: "/payment-links/settlements",
    disputes: "/payment-links/disputes",
    refunds: "/payment-links/refunds",
    reports: "/payment-links/reports",
  },
  crossBorder: {
    root: "/cross-border",
    transactions: "/cross-border/transactions",
    settlements: "/cross-border/settlements",
    disputes: "/cross-border/disputes",
    refunds: "/cross-border/refunds",
    reports: "/cross-border/reports",
    uploads: "/cross-border/uploads",
    configurations: "/cross-border/configurations",
  },
  support: {
    root: "/support",
    knowledgeHub: "/support/knowledge-hub",
    supportQueries: "/support/support-queries",
    ticketHistory: "/support/ticket-history",
    faqs: "/support/faqs",
    trainingVideos: "/support/training-videos",
  },
  settings: {
    root: "/settings",
  },
  account: {
    profile: "/account/profile",
    businessDetails: "/account/business-details",
    users: "/account/users",
    roles: "/account/users/roles",
    preferences: "/account/preferences",
    security: "/account/security",
    feedback: "/account/feedback",
  },
} as const

